# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog daijiang
url: http://xiaozhucdj.github.io
feed: /atom.xml
author_info: <a href="http://xiaozhucdj.github.io/">daijiang</a>

myblog:
  gavatar: images/2.jpg
  gpname: daijiang
  linkedin: http://www.uucars.com/
  github: https://github.com/xiaozhucdj
  email: mailto:840251792@qq.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
